# models/__init__.py — keep as-is
from . import (
    res_company,
    res_config_settings,
    fsm_model_mixin,
    fsm_category,
    fsm_template,
    res_territory,
    fsm_tag,
    fsm_stage,
    fsm_team,
    fsm_person,
    fsm_location,
    fsm_location_person,
    res_partner,
    fsm_equipment,
    fsm_order_type,
    fsm_service_type,
    fsm_equipment_condition,
    fsm_pm_frequency,
    fsm_person_calendar_filter,
    fsm_order,
    fsm_phe_unit,
    fsm_pm_schedule,
)